platform :ios, '10.0'
pod 'IronSourceSDK','7.4.0.0'

{{#iron_source.adcolony_ios}}
pod 'IronSourceAdColonyAdapter','4.3.16.2'
{{/iron_source.adcolony_ios}}

{{#iron_source.applovin_ios}}
pod 'IronSourceAppLovinAdapter','4.3.40.2'
{{/iron_source.applovin_ios}}

{{#iron_source.aps_ios}}
pod 'IronSourceAPSAdapter','4.3.8.1'
{{/iron_source.aps_ios}}

{{#iron_source.bidmachine_ios}}
pod 'IronSourceBidMachineAdapter','4.3.0.0'
{{/iron_source.bidmachine_ios}}

{{#iron_source.charboost_ios}}
pod 'IronSourceChartboostAdapter','4.3.15.1'
{{/iron_source.charboost_ios}}

{{#iron_source.csj_ios}}
pod 'IronSourceCSJAdapter', '4.3.2.2'
{{/iron_source.csj_ios}}

{{#iron_source.fyber_ios}}
pod 'IronSourceFyberAdapter','4.3.30.2'
{{/iron_source.fyber_ios}}

{{#iron_source.facebook_ios}}
pod 'IronSourceFacebookAdapter','4.3.39.2'
{{/iron_source.facebook_ios}}

{{#iron_source.admob_ios}}
pod 'IronSourceAdMobAdapter','4.3.45.1'
{{/iron_source.admob_ios}}

{{#iron_source.hyprmx_ios}}
pod 'IronSourceHyprMXAdapter','4.3.3.1'
{{/iron_source.hyprmx_ios}}

{{#iron_source.inmobi_ios}}
pod 'IronSourceInMobiAdapter','4.3.17.2'
{{/iron_source.inmobi_ios}}

{{#iron_source.liftoff_ios}}
pod 'IronSourceVungleAdapter','4.3.28.1'
{{/iron_source.liftoff_ios}}

{{#iron_source.maio_ios}}
pod 'IronSourceMaioAdapter','4.1.11.2'
{{/iron_source.maio_ios}}

{{#iron_source.mintegral_ios}}
pod 'IronSourceMintegralAdapter', '4.3.16.1'
{{/iron_source.mintegral_ios}}

{{#iron_source.mytarget_ios}}
pod 'IronSourceMyTargetAdapter','4.1.16.2'
{{/iron_source.mytarget_ios}}

{{#iron_source.pangle_ios}}
pod 'IronSourcePangleAdapter','4.3.22.1'
{{/iron_source.pangle_ios}}

{{#iron_source.smaato_ios}}
pod 'IronSourceSmaatoAdapter','4.3.10.2'
{{/iron_source.smaato_ios}}

{{#iron_source.superawesome_ios}}
pod 'IronSourceSuperAwesomeAdapter','4.1.7.2'
{{/iron_source.superawesome_ios}}

{{#iron_source.tapjoy_ios}}
pod 'IronSourceTapjoyAdapter','4.1.25.2'
{{/iron_source.tapjoy_ios}}

{{#iron_source.tencent_ios}}
pod 'IronSourceTencentAdapter','4.3.5.2'
{{/iron_source.tencent_ios}}

{{#iron_source.unityads_ios}}
pod 'IronSourceUnityAdsAdapter','4.3.31.1'
{{/iron_source.unityads_ios}}

